# -*- coding: utf-8 -*-
"""CP2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1at62JGDWP5BUEMpulHGHRHz4GwwAbcDx
"""

m=int(input())
k=[]
j=[]

for d in range(m):
    l.append(input())

s=int(input())
for c in range(s):
    j.append(input().split(','))
    
for x in l:
    for d in range(s):
        if j[d][0]==x:
            print(','.join(j[d]))