# -*- coding: utf-8 -*-
"""Diviseur d'un entier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RMYIXj8gFTTVsOxp3Ad3qbbEeLUSDv4q
"""

# This function returns a list containing all the factors of a ginven parameters n
def getFactors(n):
    # Create an empty list for factors
    factors=[];

    # Loop over all factors
    for i in range(1, n + 1):
        if n % i == 0:
            factors.append(i)

    # Return the list of factors
    return factors

# Call the function with a given value
print (getFactors(256))

