# -*- coding: utf-8 -*-
"""PGCD de 2 entiers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RMYIXj8gFTTVsOxp3Ad3qbbEeLUSDv4q
"""

# Calcul d'un PGCD par différences successives 
a=eval(input("Valeur de a ?")) 
b=eval(input("Valeur de b ?")) 
while a!=b: 
    d=abs(b-a) 
    b=a 
    a=d 
print("pgcd=",d) 
if d==1: 
    print("Les deux entiers sont premiers entre eux.")

